const documentosCurso = [
    { text: "Búsqueda secuencial: Es uno de los métodos de búsqueda más simples. Los elementos se recorren en una lista o arreglo de manera lineal desde el primero hasta el último. Se debe buscar si un valor coincide y se deja de buscar a partir de que se encuentra." },
    { text: "Utilidad de la búsqueda secuencial: Es útil en listas pequeñas y no ordenadas. Desde el índice 0 hasta n-1 evalúa si encuentra el valor y devuelve 1. Si termina el recorrido sin encontrar, devuelve -1." },
    { text: "Búsqueda binaria: Es un método más eficiente para poder realizar búsquedas sobre arreglos o listas, sin embargo, funciona únicamente con listas ordenadas. Este método divide el espacio de búsqueda a la mitad y busca reducir la cantidad de repeticiones." },
    { text: "Pasos para búsqueda binaria: 1. Toma un índice (valor medio). 2. Compara el valor con el que se desea encontrar. 3. Si es igual, finaliza; si es mayor busca en la mitad superior; si es menor busca en la mitad inferior. 4. Se sigue dividiendo en mitades hasta encontrar el valor." },
    { text: "Concepto de Hashing: Es una técnica de búsqueda rápida que se usa fundamentalmente para almacenar y acceder a datos de forma muy eficiente en estructuras de datos previamente conocidas como tablas hash. El hashing convierte una clave de entrada en un índice." },
    { text: "Función Hash y sus características: El hashing tiene como base una función hash que toma un número o una cadena (texto) de entrada y lo convierte en un índice dentro de una tabla hash. Debe ser: Determinista (misma entrada da siempre misma salida) y Uniforme (distribuye claves buscando minimizar colisiones)." },
    { text: "Tabla Hash: Estructura de datos que consiste en un arreglo de buckets o contenedores; cada posición es accesible por medio del índice generado por la función Hash. El resultado de la función se convierte en el índice de la tabla y el valor se almacena en el contenedor." },
    { text: "Pasos de búsqueda en Hashing: 1. Aplicación de la Función Hash. 2. Acceso al contenedor o bucket. 3. Verificación (especialmente necesaria en caso de colisiones)." },
    { text: "Colisiones en hashing: Si se generaran dos índices iguales, se debe aplicar una resolución de colisiones. Métodos principales: Encadenamiento (almacena una lista de elementos por cada posición) y Dirección Abierta (busca la siguiente posición en base a tres métodos)." },
    { text: "Unordered_Map en C++: Contenedor de datos asociativo, sin orden, que permite almacenamiento en pares clave -> valor. Internamente usa una tabla hash para garantizar acceso rápido y no se enfoca en el orden de las claves." },
    { text: "Operaciones de Unordered_Map: Permite inserción, búsqueda y borrado. Se usa cuando el orden no importa, se busca velocidad de acceso y se esperan muchas búsquedas." },
    { text: "Algoritmos de ordenamiento: Métodos que permiten organizar elementos de una estructura de datos para tener un orden específico, ya sea numérico o lexicográfico." },
    { text: "Función Swap: Fundamental en ordenamiento; permite el intercambio de dos valores. Toma el elemento A y lo coloca en la posición de B, y viceversa." },
    { text: "Bubble Sort (Algoritmo de Burbuja): Compara pares adyacentes y los intercambia si están en orden incorrecto, repitiendo hasta que no haya cambios. Ventajas: Sencillo de implementar, ideal para listas pequeñas. Desventaja: Ineficiente para listas grandes." },
    { text: "Selection Sort (Ordenamiento por Selección): Encuentra el elemento mínimo del arreglo y lo coloca al inicio, repitiendo para el resto. Ventajas: Fácil de entender y programar. Desventaja: Ineficiente para listas grandes." },
    { text: "Insertion Sort (Ordenamiento por Inserción): Inserta cada elemento en una lista ya ordenada acorde a su posición. Eficiente para listas pequeñas, pero ineficiente para listas muy grandes o con muchos elementos repetidos." },
    { text: "Shell Sort: Extensión de Insertion Sort que divide la lista en sublistas usando un 'gap' que se reduce progresivamente hasta llegar a 1. Aplica Insertion Sort en subarreglos. Más eficiente que Insertion Sort en listas grandes; su complejidad depende del esquema del gap." },
    { text: "Quick Sort: Divide el arreglo usando un valor pivote; reordena elementos en base a él y aplica recursividad en los subarreglos. Muy eficiente para conjuntos grandes de datos. Desventaja: Si el pivote es malo, aumenta mucho su complejidad." },
    { text: "Bogo Sort (Stupid Sort/Monkey Sort): Algoritmo muy ineficiente que genera permutaciones aleatorias (barajeo) y verifica si están ordenadas. Solo tiene fines didácticos." },
    { text: "Quickselect: Utilizado para extraer el k-ésimo elemento rápidamente sin ordenar todo el arreglo. Pasos: elegir pivote, generar partición, verificar posición del pivote y buscar a un lado u otro usando lógica de Quicksort solo en una parte." },
    { text: "Listas en programación: Estructura que permite almacenar múltiples elementos del mismo tipo de manera secuencial. Pueden crecer o reducirse dinámicamente en tiempo de ejecución, siendo útiles cuando los datos cambian constantemente." },
    { text: "Ventajas de las listas: Rapidez en inserción y eliminación, tamaño dinámico, uso de memoria adaptable (no reubican datos físicamente en bloques contiguos necesariamente) y eficiencia en reordenamientos." },
    { text: "Desventajas de las listas: Acceso secuencial (no aleatorio), mayor uso de memoria por punteros, ordenamiento más costoso y mayor complejidad en implementación/mantenimiento." },
    { text: "Manejo de listas en C++: Se utilizan principalmente std::list (Listas Doblemente Enlazadas) y std::forward_list (Listas Simplemente Enlazadas)." },
    { text: "Lista simplemente enlazada: Cada nodo tiene un apuntador únicamente hacia el siguiente nodo. Es más ligera y rápida cuando no se requiere retroceder en la lectura de datos." },
    { text: "Lista doblemente enlazada: Cada nodo tiene un apuntador al siguiente y otro al anterior. Permite acceso bidireccional y hace más eficiente la eliminación de elementos." },
    { text: "Operaciones básicas de listas en C++: Inserción (push_back, push_front), Eliminación (pop_back, pop_front, remove), Iteración (begin, end) y Limpieza (clear)." },
    { text: "Arreglo multidimensional: Extensión de un arreglo que permite almacenamiento múltiple de filas (tablas). Lo común son 2 dimensiones (filas y columnas) o 3, aunque permite más. Útiles para tableros y juegos." },
    { text: "Características de arreglos multidimensionales: Almacenamiento contiguo en memoria, acceso mediante índices [i][j], requieren ciclos dobles para recorrido y tienen tamaño fijo al crearse." },
    { text: "Arreglo en C++: Estructura que almacena un grupo de elementos del mismo tipo bajo un mismo nombre, guardándose físicamente de manera contigua en memoria." },
    { text: "Índices en arreglos: Van desde 0 hasta n-1. Facilitan el acceso y garantizan el orden. Se suelen recorrer mediante ciclos (for/while)." },
    { text: "Arreglo tradicional en C++: Tienen tamaño fijo definido en tiempo de compilación. Eficientes en memoria y acceso, manejan buffers fijos, pero no verifican límites de acceso (out of bounds)." },
    { text: "std::array: Estructura que almacena datos directo en el stack con tamaño fijo. Su inicialización es más clara que el arreglo tradicional y permite usar el método .size()." },
    { text: "std::vector: Contenedor dinámico que crece y decrece. Garantiza almacenamiento contiguo y posee métodos como push_back, insert y erase. Requiere cuidado con la gestión de memoria al redimensionarse." },
    { text: "Cadenas de texto en C++: Arreglo unidimensional de caracteres para datos alfanuméricos. Se manejan como std::string o arreglos de caracteres (char[])." },
    { text: "Funciones strlen, strcpy y strcmp: 'strlen' devuelve la longitud; 'strcpy' copia una cadena en otra; 'strcmp' compara igualdad (devuelve 0 si son iguales)." },
    { text: "Funciones strncmp, strcat y strncat: 'strncmp' compara limitando el número de caracteres; 'strcat' concatena texto a una variable; 'strncat' concatena limitando caracteres añadidos." },
    { text: "Funciones strchr, strrchr y strstr: 'strchr' busca la primera coincidencia de un carácter; 'strrchr' busca la última; 'strstr' busca la primera coincidencia de una subcadena completa." },
    { text: "Función strtok: Se utiliza para separar o dividir una cadena en tokens más pequeños usando delimitadores definidos (como espacios o comas)." },
    { text: "std::string vs char[]: Los arreglos de caracteres necesitan tamaño definido y '\\0' (nulo) al final. std::string es un contenedor dinámico que gestiona la memoria automáticamente y tiene métodos integrados." },
// ... (continuación de los anteriores)
    { text: "Concatenación en std::string: Para unir textos se utiliza el operador '+' (ejemplo: a + b) o la función integrada .append()." },
    { text: "Tamaño de std::string: Se obtiene utilizando las funciones .size() o .length(), las cuales devuelven la cantidad de caracteres." },
    { text: "Acceso a caracteres en std::string: Se puede acceder como un arreglo usando corchetes (variable[posicion]) o mediante la función .at(), que es más segura." },
    { text: "Comparación de std::string: Se pueden comparar directamente con otra variable string o una cadena literal usando el operador de comparación ==." },
    { text: "Subcadenas y búsqueda en std::string: .substr() extrae una porción indicando inicio y longitud. .find() busca la posición de una subcadena dentro de otra." },
    { text: "Arreglo de objetos: Estructura que almacena múltiples instancias de una clase en posiciones contiguas de memoria. Se maneja como un arreglo normal, pero con tipos de datos creados por el programador." },
    { text: "Uso de arreglos de objetos: Recomendado para colecciones de entidades (estudiantes, empleados) que agrupan diferentes tipos nativos y para aplicar operaciones conjuntas en POO." },
    { text: "Características de arreglos de objetos: Son homogéneos (misma clase), requieren índices, tamaño fijo al crearse y usan constructores por defecto. Se accede a atributos mediante el punto (.)." },
    { text: "Abstracción en POO: Proceso de ocultar detalles internos de una clase y mostrar solo la información esencial para utilizar el objeto." },
    { text: "Ventajas de la abstracción: Reduce complejidad, fomenta la reutilización, encapsula y protege la información, y facilita el mantenimiento interno sin afectar a otras clases." },
    { text: "Modelado de clases: Diseño de clases que trasladan objetos reales al mundo lógico. Mejores prácticas: nombres claros, encapsulamiento (privado/público), usar constructores y separar responsabilidades." },
    { text: "Método Constructor: Función que inicializa una instancia de clase. Se ejecuta automáticamente al crear el objeto, tiene el mismo nombre de la clase y no tiene tipo de retorno (ni siquiera void)." },
    { text: "Herencia en POO: Concepto donde una subclase (clase derivada) adquiere los atributos y métodos de una Superclase (clase base)." },
    { text: "Tipos de herencia en C++: Pública (mantiene niveles public/protected), Protegida (public/protected pasan a ser protected en la subclase) y Privada (public/protected pasan a ser private)." },
    { text: "Concepto de Struct en C++: Estructura que agrupa múltiples variables de diferentes tipos bajo un solo nombre. Funciona como plantilla para organizar datos complejos." },
    { text: "Características de Struct: Acceso público por defecto (a diferencia de las clases), compatible con C, permite crear arreglos o matrices de estructuras." },
    { text: "Ventajas y desventajas de Structs: Ventajas: organización simple y código simplificado. Desventajas: brechas de seguridad por ser públicos y falta de funciones avanzadas como herencia o polimorfismo." },
    { text: "Declaración de Struct: Requiere la palabra reservada 'struct', nombre, llaves de apertura/cierre y los tipos de datos internos." },
    { text: "Cuándo usar Struct: Recomendable cuando solo se guardan datos sin lógica de métodos, el acceso puede ser público y no se requiere arquitectura compleja de objetos." },
    { text: "Estructuras (Struct) como plantillas: Sirven para encapsular variables facilitando su acceso y organización, agrupando datos heterogéneos bajo un mismo identificador." },
// ... (continuación de los anteriores)
    { text: "Características de Struct: Agrupa datos bajo un mismo nombre, acceso público por defecto (sin private/protected), compatible con lenguaje C y permite crear arreglos o matrices de estructuras." },
    { text: "Ventajas y desventajas de Structs: Ventajas: organización y flexibilidad con datos simples. Desventajas: posibles brechas de seguridad por ser públicos y falta de herencia/polimorfismo." },
    { text: "Componentes de un Struct: Palabra reservada 'struct', nombre, llaves de apertura/cierre y declaración de datos internos con sus tipos." },
    { text: "Cuándo usar Struct: Para almacenamiento puro de datos sin lógica de métodos, cuando el acceso puede ser público y no se requiere una arquitectura de objetos compleja." },
    { text: "Punteros en C++: Característica que permite trabajar con direcciones de memoria. Un puntero es una variable que almacena la dirección de memoria de otra variable." },
    { text: "Ventajas de punteros: Eficiencia al modificar memoria directamente, facilitan la gestión de Memoria Dinámica y permiten el Paso por Referencia (enviar datos sin copiarlos)." },
    { text: "Riesgos de punteros: Fugas de memoria (memory leaks) si no se libera, dificultad en depuración y riesgo de punteros colgantes (dangling pointers) que apuntan a memoria ya liberada." },
    { text: "Operadores & y *: '&' obtiene la dirección de memoria de una variable. '*' obtiene el valor almacenado en una dirección de memoria específica (desreferenciación)." },
    { text: "Aspectos críticos de punteros: Siempre deben inicializarse (ej. con nullptr) para evitar direcciones aleatorias. Pueden usarse con arreglos, otros punteros o como parámetros de funciones." },
    { text: "Manejo de memoria dinámica: Se usa 'new' para reservar memoria (ej. int* p = new int;) y 'delete' para liberarla cuando ya no se necesita (ej. delete p;)." },
    { text: "Sobrecarga en C++: Ocurre cuando métodos o funciones tienen el mismo nombre pero se diferencian obligatoriamente en el número o tipo de parámetros. Existe sobrecarga de funciones y de métodos." },
    { text: "Tipos de sobrecarga: Principalmente sobrecarga de funciones (globales) y sobrecarga de métodos (dentro de clases)." },
    { text: "Concepto de Polimorfismo: Significa 'muchas formas'. En programación, permite que un mismo método se comporte de forma diferente según el objeto que lo invoque." },
    { text: "Implementación de Polimorfismo: Requiere una clase base con métodos 'virtual', clases derivadas que sobreescriban esos métodos y el uso de punteros/referencias al tipo base para la invocación dinámica." },
    { text: "Importancia del Polimorfismo: Pilar de la POO que otorga reutilización de código, facilidad de mantenimiento y gran flexibilidad al sistema." },
    { text: "Funciones Virtuales: Herramienta clave para el polimorfismo en tiempo de ejecución. Se declaran con 'virtual' en la clase base para permitir que las derivadas adapten el comportamiento." },
    { text: "Valor nulo en punteros: Se usa 'nullptr' en C++ moderno para indicar que un puntero no apunta a ninguna dirección válida, limpiándolo efectivamente." },
    { text: "Diferencia NULL vs nullptr: Aunque NULL se usaba antes, 'nullptr' es la mejor práctica en el estándar moderno de C++ para mayor seguridad tipada." },
    { text: "Inicialización de punteros: Es vital inicializar con 'nullptr' para evitar punteros 'salvajes'. Permite validar si un puntero está en uso mediante una condición antes de acceder a él." },
    { text: "Puntero a función: Característica avanzada que almacena la dirección de una función en una variable, permitiendo selección dinámica en tiempo de ejecución. Sintaxis: retorno (*nombrePuntero)(parametros);" },
    // ... (continuación de los anteriores)
    { text: "Aplicaciones de punteros a funciones: Permiten pasar parámetros en tiempo real y son útiles al asociarse con arreglos. Facilitan la creación de menús y reducen el uso excesivo de switch-case o if-else." },
    { text: "Recursividad: Concepto donde una función se llama a sí misma para resolver un problema. Descompone problemas complejos en subproblemas similares y depende de su propia ejecución definida." },
    { text: "Cuándo usar recursividad: Recomendado para estructuras de árboles, grafos o problemas que se descomponen naturalmente en subproblemas. Ofrece código más claro en permutaciones o combinaciones." },
    { text: "Componentes de un método recursivo: 1. Caso Base (condición de terminación para evitar recursividad infinita). 2. Caso Recursivo (parte donde el método se invoca a sí mismo)." },
    { text: "Ventajas y riesgos de recursividad: Ventajas: simplificación y reducción de código. Riesgos: mayor consumo de memoria, lentitud si no se implementa bien y riesgo de Stack Overflow." },
    { text: "Diferencia Iteración vs Recursividad: La recursividad es mejor para problemas divisibles (como árboles) y depende de la pila (stack) de C++. La iteración es mejor para tareas simples como recorrer listas." },
    { text: "Clasificación de datos en C++: 1. Datos Primitivos. 2. Datos Derivados. 3. Datos Definidos por el Usuario. Determina los valores almacenables y las operaciones permitidas." },
    { text: "Datos primitivos en C++: Se dividen en Tipos Enteros (int, short, long, long long, unsigned) y Tipos de Punto Flotante (float, double)." },
    { text: "Datos derivados: Construidos a partir de primitivos. Incluyen Arreglos, Apuntadores, Referencias, Estructuras (Structs), Uniones y Enumeraciones." },
    { text: "Datos definidos por el usuario: Las Clases son el ejemplo principal, permitiendo crear objetos que encapsulan datos (atributos) y comportamiento (métodos)." },
    { text: "Interfaz en C++: Contrato que define qué hace una clase pero no cómo. Declara métodos sin implementación (puros), obligando a las clases derivadas a proporcionarla." },
    { text: "Método Virtual Puro: Función declarada en clase base sin implementación. En C++ se identifica por terminar en '= 0' (ejemplo: virtual void funcion() = 0;)." },
    { text: "Clase Abstracta Pura: Debe tener al menos una función pura virtual, no puede ser instanciada directamente y sirve exclusivamente como base para otras clases." },
    { text: "Ventajas de Interfaces: Separan el 'qué' del 'cómo', fomentan el polimorfismo, permiten desarrollo en capas (desacoplamiento) y mejoran la escalabilidad y mantenimiento." },
    { text: "Modificadores de acceso: Herramientas de POO para controlar visibilidad de miembros. Facilitan el encapsulamiento y la seguridad al determinar quién accede a qué parte del código." },
    { text: "Niveles public, protected y private: 'public' es acceso total. 'protected' permite acceso a la clase y sus herederas. 'private' restringe el acceso únicamente a la propia clase." },
    { text: "Sobrecarga de métodos: Permite usar el mismo nombre para múltiples funciones. Deben diferenciarse en cantidad o tipo de parámetros (el tipo de retorno solo no basta)." },
    { text: "Ventajas de sobrecarga: Aporta claridad al usar nombres similares para acciones parecidas, permite reutilización de código y facilita el uso al usuario final." },
    { text: "Paradigma de programación: Enfoque o estilo adoptado por una comunidad para estructurar y organizar el código fuente al solucionar problemas." },
    { text: "Paradigma Imperativo vs Estructurado: El Imperativo (1940s) es de baja abstracción y enfocado en instrucciones directas (como Assembly). El Estructurado (1970s) usa subrutinas, bucles y condicionales para mayor claridad." },
    // ... (continuación de los anteriores)
    { text: "POO y sus pilares: Paradigma basado en 'objetos' con atributos (datos) y métodos (código). Sus cuatro pilares son Abstracción, Encapsulamiento, Herencia y Polimorfismo." },
    { text: "Clase vs Objeto: Una Clase es la plantilla o molde que define atributos y comportamientos. Un Objeto es la instancia específica de esa clase con valores propios." },
    { text: "Encapsulamiento y Herencia: El encapsulamiento agrupa datos/métodos y restringe el acceso interno para proteger la integridad. La herencia permite crear clases nuevas basadas en existentes para reutilizar código." },
    { text: "Ejercicio Calculadora Compleja: Proyecto de 3 fases: 1. Clase base con operaciones básicas. 2. Herencia para añadir raíz y potencia. 3. Sobrecarga de métodos para aceptar hasta 3 parámetros." },
    { text: "Validaciones en Calculadora: Es fundamental validar la entrada de datos y el funcionamiento lógico al solicitar números para asegurar que las operaciones devuelvan el resultado esperado." },
    { text: "Sobrecarga en Calculadora (Fase 3): Se implementa para que los métodos acepten 2 o 3 números. El programa debe consultar al usuario cuántos operandos usará y llamar al método sobrecargado correcto." },
    { text: "Nodo de Lista Doblemente Enlazada: Contiene un objeto de datos (ej. Estudiante), un puntero 'siguiente' y un puntero 'anterior'. Ambos deben inicializarse en 'nullptr' en el constructor para seguridad." },
    { text: "Insertar al final (Lista Doble): Se usa 'new' para el nodo. Si está vacía, el nodo es cabeza y cola. Si no, el 'siguiente' de la cola apunta al nuevo, el 'anterior' del nuevo apunta a la antigua cola, y se actualiza la cola." },
    { text: "Eliminar nodo (Lista Doble): Se recorre hasta hallar el nodo (ej. por carnet). Se reconectan los adyacentes: el 'siguiente' del anterior apunta al 'siguiente' del actual, y el 'anterior' del siguiente apunta al 'anterior' del actual. Se usa 'delete'." },
    { text: "Recorrido de Lista Doble: Se usa un puntero auxiliar 'actual' que inicia en cabeza. Con un ciclo while (actual != nullptr), se accede a los datos y se avanza mediante actual = actual->siguiente." },
    { text: "Nodo de Lista Simplemente Enlazada: Compuesto por la información (objeto) y un único puntero 'siguiente'. El puntero debe inicializarse como 'nullptr' para marcar el final de la lista." },
    { text: "Insertar al final (Lista Simple): Se crea nodo con 'new'. Si está vacía, la cabeza apunta al nuevo. Si no, un auxiliar recorre hasta el último nodo (donde siguiente es nullptr) y lo conecta al nuevo." },
    { text: "Eliminar nodo (Lista Simple): Se recorre buscando el nodo. Si es la cabeza, se mueve el puntero cabeza al siguiente. Si es intermedio, el 'siguiente' del anterior salta el nodo actual. Es obligatorio usar 'delete' para liberar memoria." },
    { text: "Verificación y recorrido (Lista Simple): Se verifica si está vacía comprobando si cabeza == nullptr. Para mostrar datos, se recorre desde la cabeza imprimiendo cada nodo hasta que el puntero sea nulo." }
];

module.exports = documentosCurso;